# Dockerfile for FirstApp
FROM ubuntu
RUN mkdir /app
WORKDIR /app

# Copy the 'Modules' directory
COPY ../Modules /app/Modules

# Copy application files
COPY file1 /app/file1
COPY file2 /app/file2

# Any additional instructions to build the application

