FROM ubuntu

RUN mkdir /app
WORKDIR /app

# Copy the 'Modules' directory
COPY Modules /app/Modules

# Copy application files
COPY SecondApp/file1 /app/FirstApp/file1
COPY SecondApp/file2 /app/FirstApp/file2
