# Final image
FROM ubuntu

RUN mkdir /app
WORKDIR /app

# Copy application files from the builder stage

# Copy additional application files
COPY FirstApp/file1 /app/FirstApp/file1
COPY FirstApp/file2 /app/FirstApp/file2

